"""Modify Todos Columns

Revision ID: 06dfe91ddf9a
Revises: c706c7317698
Create Date: 2023-09-08 17:48:30.639227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dfe91ddf9a'
down_revision = 'c706c7317698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
