"""Modify Todos

Revision ID: 1e07c74c2100
Revises: 8fecef9198f1
Create Date: 2023-09-08 18:08:17.461323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e07c74c2100'
down_revision = '8fecef9198f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
