"""Modify Todos and users Columns changes done

Revision ID: 20b4e2fb4384
Revises: 5c5ed1af933a
Create Date: 2023-09-10 12:34:31.916201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b4e2fb4384'
down_revision = '5c5ed1af933a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TODOS', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_TODOS_owner_id_users'), 'TODOS', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    op.drop_constraint(op.f('fk_TODOS_owner_id_users'), 'TODOS', type_='foreignkey')
    op.drop_column('TODOS', 'owner_id')
    # ### end Alembic commands ###
