"""Modify Todos

Revision ID: 21c1b286d767
Revises: ece6876d6a65
Create Date: 2023-09-08 10:41:04.156781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c1b286d767'
down_revision = 'ece6876d6a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
