"""Modify Todos and users Columns changes done

Revision ID: 225b1eec7b91
Revises: 20b4e2fb4384
Create Date: 2023-09-11 18:39:08.595958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225b1eec7b91'
down_revision = '20b4e2fb4384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
