"""Modify Todos

Revision ID: 4e518eba247f
Revises: b7a5aa41f834
Create Date: 2023-09-08 11:53:15.032784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e518eba247f'
down_revision = 'b7a5aa41f834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
