"""Modify Todos Columns dur added1

Revision ID: 5c5ed1af933a
Revises: b4d9ccc26dfc
Create Date: 2023-09-09 17:59:03.497388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5ed1af933a'
down_revision = 'b4d9ccc26dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TODOS', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TODOS', 'duration')
    # ### end Alembic commands ###
