"""Modify Todos Columns duration

Revision ID: 7e62c4c77841
Revises: b23b5b298412
Create Date: 2023-09-09 17:21:20.846328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e62c4c77841'
down_revision = 'b23b5b298412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
