"""Modify Todos Columns

Revision ID: 8fecef9198f1
Revises: 06dfe91ddf9a
Create Date: 2023-09-08 17:51:08.396200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fecef9198f1'
down_revision = '06dfe91ddf9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_TODOS_duration'), 'TODOS', ['duration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TODOS_duration'), table_name='TODOS')
    # ### end Alembic commands ###
