"""Modify Todos Columns

Revision ID: b23b5b298412
Revises: c7f83d218e6d
Create Date: 2023-09-08 22:49:22.006716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23b5b298412'
down_revision = 'c7f83d218e6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
