"""Modify Todos Columns dur

Revision ID: b4d9ccc26dfc
Revises: 7e62c4c77841
Create Date: 2023-09-09 17:30:02.042093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4d9ccc26dfc'
down_revision = '7e62c4c77841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_TODOS_duration', table_name='TODOS')
    op.drop_column('TODOS', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TODOS', sa.Column('duration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_TODOS_duration', 'TODOS', ['duration'], unique=False)
    # ### end Alembic commands ###
