"""Modify Todos

Revision ID: b7a5aa41f834
Revises: 21c1b286d767
Create Date: 2023-09-08 11:25:25.831230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a5aa41f834'
down_revision = '21c1b286d767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
