"""Modify Todos

Revision ID: c019f02d6f71
Revises: 4e518eba247f
Create Date: 2023-09-08 16:50:41.083357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c019f02d6f71'
down_revision = '4e518eba247f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
