"""Todos Tables

Revision ID: c0b284a73a58
Revises: 980adae6df2b
Create Date: 2023-09-07 23:14:11.996250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b284a73a58'
down_revision = '980adae6df2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TODOS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TODOS'))
    )
    op.create_index(op.f('ix_TODOS_description'), 'TODOS', ['description'], unique=False)
    op.create_index(op.f('ix_TODOS_id'), 'TODOS', ['id'], unique=False)
    op.create_index(op.f('ix_TODOS_status'), 'TODOS', ['status'], unique=False)
    op.create_index(op.f('ix_TODOS_task_name'), 'TODOS', ['task_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TODOS_task_name'), table_name='TODOS')
    op.drop_index(op.f('ix_TODOS_status'), table_name='TODOS')
    op.drop_index(op.f('ix_TODOS_id'), table_name='TODOS')
    op.drop_index(op.f('ix_TODOS_description'), table_name='TODOS')
    op.drop_table('TODOS')
    # ### end Alembic commands ###
