"""Modify Todos

Revision ID: c706c7317698
Revises: c019f02d6f71
Create Date: 2023-09-08 17:23:20.613316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c706c7317698'
down_revision = 'c019f02d6f71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
