"""Modify Todos Columns

Revision ID: c7f83d218e6d
Revises: 58b68396b935
Create Date: 2023-09-08 18:56:30.856702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f83d218e6d'
down_revision = '58b68396b935'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
