"""Modify Todos

Revision ID: ece6876d6a65
Revises: c0b284a73a58
Create Date: 2023-09-08 10:39:44.009528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece6876d6a65'
down_revision = 'c0b284a73a58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
